version: "3.3"

services:
  gunicorn_web:
    build:
      context: ../../
      dockerfile: docker/site-edit-2/Dockerfile
    entrypoint: /code/docker/site-edit-2/docker-entrypoint-gunweb.sh
    volumes:
      - ../../:/code
      - docker_emlo_home:/emlo_home
    ports:
      - "8000:8000"
    env_file:
      - .gunweb.env
    depends_on:
      - db

  nginx:
    build:
      context: ../../
      dockerfile: docker/site-edit-2/nginx.Dockerfile
    volumes:
      - docker_emlo_home:/emlo_home
    ports:
      - 8010:80
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - gunicorn_web

  db: 
    env_file:
      - .gunweb.env
volumes:
  data:
  docker_emlo_home:
