version: "3.3"

services:
  gunicorn_web:
    build:
      context: ../../
      dockerfile: docker/site-edit-2/Dockerfile
    entrypoint: /code/docker/site-edit-2/docker-entrypoint-gunweb.sh
    volumes:
      - ../../:/code
      - ~/docker_emlo_home:/emlo_home
    ports:
      - "8000:8000"
    env_file:
      - .gunweb.env
    depends_on:
      - db

  nginx:
    build:
      context: ../../
      dockerfile: docker/site-edit-2/nginx.Dockerfile
    volumes:
      - ~/docker_emlo_home:/emlo_home
    ports:
      - 8010:80
        # environment:
        #         # - NGINX_HOST=192.168.56.10
        #   - NGINX_PORT=80
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - gunicorn_web

  db: 
    env_file:
      - .gunweb.env

    
  # db:
  #   image: postgres
  #   volumes:
  #     - data:/var/lib/postgresql/data
  #   env_file:
  #     - .env
  #   ports:
  #     - 25432:5432
  # web:
  #   build:
  #     context: ../../
  #     dockerfile: docker/site-edit-2/Dockerfile
  #   #command: python manage.py runserver 0.0.0.0:8000
  #   entrypoint: /code/docker/site-edit-2/docker-entrypoint.sh
  #   volumes:
  #     - ../../:/code
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=name@example.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - "5050:80"
  #   links:
  #     - db
  #   depends_on:
  #     - db
volumes:
  data:
