version: "3.3"

services:

  db:
    image: postgres:14
    environment:
      PGDATA: /var/lib/postgresql/data/emlo_db/
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 25432:5432

  web:
    build:
      context: ../../
      dockerfile: docker/site-edit-2/Dockerfile
    volumes:
      - ../../:/code
      - emlo_home:${EMLO_APP_HOME}
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=name@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    links:
      - db
    depends_on:
      - db
volumes:
  data:
  emlo_home:
